# Generated by Django 3.0.5 on 2020-04-18 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classroom',
            old_name='scheduled_by',
            new_name='schedule_id',
        ),
    ]
