# Generated by Django 3.0.5 on 2020-04-18 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_invitedlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classroom',
            old_name='class_name',
            new_name='class_unique_name',
        ),
        migrations.RemoveField(
            model_name='scheduleclass',
            name='class_id',
        ),
    ]
