# Generated by Django 3.0.5 on 2020-04-18 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_auto_20200418_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='class_unique_name',
            field=models.CharField(max_length=100),
        ),
    ]
