# Generated by Django 3.0.5 on 2020-04-18 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_auto_20200418_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitedlist',
            name='twilio_sid',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
