# Generated by Django 3.0.5 on 2020-04-22 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0006_invitedlist_twilio_sid'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitedlist',
            name='class_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='landing.ClassRoom'),
            preserve_default=False,
        ),
    ]
