# Generated by Django 3.0.5 on 2020-04-22 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0007_invitedlist_class_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitedlist',
            name='class_name',
        ),
    ]
